### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by gregbugaj** [marieai/marie-ai#62]
Some documents throw following exception

```
ERROR  BoxProcessorUlimDit@321636                                                                                                                                                               [04/14/23 18:47:03]
Traceback (most recent call last):
  File "/home/gbugaj/environments/pytorch2-3.10/lib/python3.10/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/gbugaj/environments/pytorch2-3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "/home/gbugaj/environments/pytorch2-3.10/lib/python3.10/site-packages/gradio/blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/gbugaj/environments/pytorch2-3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/gbugaj/environments/pytorch2-3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/gbugaj/environments/pytorch2-3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/gbugaj/dev/marieai/marie-ai/workspaces/pipeline-gradio/./app.py", line 120, in process_image
    ) = box_processor.extract_bounding_boxes("gradio", "field", image, PSMode.SPARSE)
  File "/home/gbugaj/dev/marieai/marie-ai/marie/boxes/dit/ulim_dit_box_processor.py", line 404, in extract_bounding_boxes
    raise ex
  File "/home/gbugaj/dev/marieai/marie-ai/marie/boxes/dit/ulim_dit_box_processor.py", line 309, in extract_bounding_boxes
    bboxes, polys, scores, lines_bboxes, classes = self.psm_sparse(image)
TypeError: cannot unpack non-iterable NoneType object

```

**Comment by gregbugaj** [comment]
Resolved with commit https://github.com/marieai/marie-ai/commit/fb003f285e7241199b60a177149fd7a8f4dd96b4
