### ISSUE TITLE
cache resources exhausted 

### ISSUE THREAD

**Issue by gregbugaj** [marieai/marie-ai#93]
**Describe the bug**
WAND is running out of resources while trying to cache a document.

```
ERROR  marie@34 Extract error : cache resources exhausted `/tmp/tmpelx96q62/PID_5805_12996_0_190925873_00005.tif' @ error/cache.c/OpenPixelCache/4095            [11/28/23 23:21:00]
       Traceback (most recent call last):                                                                                                                                           
         File "/opt/venv/lib/python3.10/site-packages/marie/executor/classifier/document_classifier_executor.py", line 211, in classify                                             
           metadata = self.pipeline.execute(                                                                                                                                        
         File "/opt/venv/lib/python3.10/site-packages/marie/pipe/classification_pipeline.py", line 213, in execute                                                                  
           return self.execute_frames_pipeline(                                                                                                                                     
         File "/opt/venv/lib/python3.10/site-packages/marie/pipe/classification_pipeline.py", line 137, in execute_frames_pipeline                                                  
           burst_frames(ref_id, frames, root_asset_dir)                                                                                                                             
         File "/opt/venv/lib/python3.10/site-packages/marie/pipe/components.py", line 380, in burst_frames                                                                          
           burst_tiff_frames(frames, output_dir, filename_generator=filename_generator)                                                                                             
         File "/opt/venv/lib/python3.10/site-packages/marie/utils/tiff_ops.py", line 130, in burst_tiff_frames                                                                      
           __process_burst(                                                                                                                                                         
         File "/opt/venv/lib/python3.10/site-packages/marie/utils/tiff_ops.py", line 100, in __process_burst                                                                        
           raise ident                                                                                                                                                              
         File "/opt/venv/lib/python3.10/site-packages/marie/utils/tiff_ops.py", line 98, in __process_burst                                                                         
           convert_group4(output_path_tmp, output_path)                                                                                                                             
         File "/opt/venv/lib/python3.10/site-packages/marie/utils/tiff_ops.py", line 48, in convert_group4                                                                          
           with Image(filename=src_path) as image:                                                                                                                                  
         File "/opt/venv/lib/python3.10/site-packages/wand/image.py", line 9382, in __init__                                                                                        
           self.read(filename=filename)                                                                                                                                             
         File "/opt/venv/lib/python3.10/site-packages/wand/image.py", line 10137, in read                                                                                           
           self.raise_exception()                                                                                                                                                   
         File "/opt/venv/lib/python3.10/site-packages/wand/resource.py", line 225, in raise_exception                                                                               
           raise e                                                                                                                                                                  
       wand.exceptions.CacheError: cache resources exhausted `/tmp/tmpelx96q62/PID_5805_12996_0_190925873_00005.tif' @ error/cache.c/OpenPixelCache/4095  
```
**Describe how you solve it**

---

**Environment**
3.0.24:cuda

**Screenshots**

**Comment by gregbugaj** [comment]
Closed by #95
